server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://homeview2.czjfbvb9lfo4.ap-northeast-2.rds.amazonaws.com:3306/homeview4
    username: admin
    password: 20230529a

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: homeview-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIARQZ7J7WB3GA4HV46
      secret-key: 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

